
spring.application.name=bookmark

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=myuser
spring.datasource.password=mypass

# spring.datasource.driver-class-name=org.postgresql.Driver - Dependecy already provides driver

# Tells Hibernate to manage and generate database schema from entity class. NOTE: Change "none" to "update" later to create entity
spring.jpa.hibernate.ddl-auto=none
# Print the SQL queries you're generating to the terminal
spring.jpa.show-sql=true 